/** @type {import('tailwindcss').Config} */
export default {
	content: ['./src/mainview/**/*.{html,js,ts,jsx,tsx}'],
	theme: {
		extend: {
			colors: {
				'surface-container-low': '#f3f4f0',
				'on-error-container': '#93000a',
				'on-tertiary-container': '#79474b',
				'on-secondary-fixed': '#011f2a',
				'on-background': '#1a1c1a',
				tertiary: '#835053',
				'on-secondary': '#ffffff',
				'on-surface-variant': '#414943',
				'outline-variant': '#c1c8c1',
				'tertiary-fixed': '#ffdadb',
				'on-surface': '#1a1c1a',
				'secondary-fixed': '#cbe7f6',
				'primary-fixed-dim': '#a4d1b6',
				primary: '#3d6751',
				'on-primary-fixed-variant': '#254f3a',
				'secondary-fixed-dim': '#afcbda',
				'surface-container-highest': '#e2e3df',
				'on-tertiary-fixed': '#340f13',
				'inverse-surface': '#2f312f',
				'error-container': '#ffdad6',
				'on-primary-fixed': '#002113',
				'inverse-on-surface': '#f0f1ed',
				'tertiary-fixed-dim': '#f7b6b9',
				'on-tertiary-fixed-variant': '#68393d',
				'on-secondary-container': '#4c6673',
				'primary-container': '#a8d5ba',
				'secondary-container': '#c8e4f3',
				background: '#f9faf6',
				'surface-container-lowest': '#ffffff',
				'on-error': '#ffffff',
				'tertiary-container': '#fcbabd',
				'surface-dim': '#d9dad7',
				'inverse-primary': '#a4d1b6',
				'surface-container-high': '#e8e8e5',
				secondary: '#48626f',
				'on-primary': '#ffffff',
				'on-tertiary': '#ffffff',
				'on-primary-container': '#345d48',
				'primary-fixed': '#bfedd1',
				outline: '#717973',
				error: '#ba1a1a',
				surface: '#f9faf6',
				'on-secondary-fixed-variant': '#304a57',
				'surface-variant': '#e2e3df',
				'surface-bright': '#f9faf6',
				'surface-container': '#edeeeb',
			},
			fontFamily: {
				sans: ['Plus Jakarta Sans', 'sans-serif'],
			},
			fontSize: {
				h1: ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
				h2: ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '500' }],
				h3: ['20px', { lineHeight: '28px', letterSpacing: '0', fontWeight: '500' }],
				'body-sm': ['14px', { lineHeight: '20px', letterSpacing: '0', fontWeight: '400' }],
				'body-md': ['16px', { lineHeight: '24px', letterSpacing: '0', fontWeight: '400' }],
				'body-lg': ['18px', { lineHeight: '28px', letterSpacing: '0', fontWeight: '400' }],
				'label-sm': ['10px', { lineHeight: '12px', letterSpacing: '0.05em', fontWeight: '600' }],
				'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.04em', fontWeight: '600' }],
				display: ['40px', { lineHeight: '48px', letterSpacing: '-0.02em', fontWeight: '600' }],
			},
			spacing: {
				xs: '4px',
				sm: '8px',
				md: '16px',
				lg: '24px',
				xl: '32px',
				xxl: '48px',
				gutter: '24px',
				margin: '32px',
			},
			borderRadius: {
				none: '0',
				sm: '4px',
				md: '8px',
				lg: '16px',
				xl: '24px',
				full: '9999px',
			},
		},
	},
	plugins: [],
};
